import Image from 'next/image'
import Head from 'next/head'
import { Form } from '../components/ui/Form/Form'
import styles from '../styles/Home.module.css'
import { MetaHome } from '../components/meta/Home/MetaHome'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='w-300'>
          <Form
            data={MetaHome.fields}
            submit={{
              value: "Entrar",
              className: "btn btn-primary w-100 h40"
            }}
          />
        </div>
      </main>
    </div>
  )
}
